name: udetxen
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.0.5
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  get_it: ^7.7.0
  flutter_local_notifications: ^17.2.2
  flutter_spinkit: ^5.2.1
  flutter_bloc: ^8.1.6
  mime: ^2.0.0
  image_picker: ^1.1.2
  http_parser: ^4.0.2
  audioplayers: ^6.1.0
  video_player: ^2.9.2
  fl_chart: ^0.69.2
  google_mlkit_translation: ^0.11.0
  easy_localization: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/langs/
